"""empty message

Revision ID: 8a96208940ac
Revises: 86888a00092f
Create Date: 2024-12-16 14:45:28.829007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a96208940ac'
down_revision = '86888a00092f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('card_holder_name')
        batch_op.drop_column('cvc')
        batch_op.drop_column('expire_month')
        batch_op.drop_column('expire_year')
        batch_op.drop_column('card_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('expire_year', sa.VARCHAR(length=4), nullable=False))
        batch_op.add_column(sa.Column('expire_month', sa.VARCHAR(length=2), nullable=False))
        batch_op.add_column(sa.Column('cvc', sa.VARCHAR(length=4), nullable=False))
        batch_op.add_column(sa.Column('card_holder_name', sa.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
