"""Added is_read  to ContactMessage

Revision ID: 99201297e23f
Revises: 8a96208940ac
Create Date: 2024-12-16 19:09:27.445692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99201297e23f'
down_revision = '8a96208940ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
